# Generated by Django 5.0.3 on 2024-05-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.TextField(max_length=255)),
                ("user_age", models.IntegerField()),
            ],
        ),
    ]
