# Generated by Django 5.0.3 on 2024-05-25 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_user_registration", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Users",
            new_name="User",
        ),
    ]
